FROM node:8.5.0

RUN useradd --user-group --create-home --shell /bin/false envuser
ENV HOME=/home/envuser

COPY app/package.json $HOME/apphome/
RUN chown -R envuser:envuser $HOME/*

USER envuser

WORKDIR $HOME/apphome

RUN npm install

EXPOSE 10001
CMD ["npm", "start"]
