FROM node:8.4.0

RUN useradd --user-group --create-home --shell /bin/false edca
ENV HOME=/home/edca

COPY package.json $HOME/api/
RUN chown -R edca:edca $HOME/*

USER edca

WORKDIR $HOME/api

RUN npm install

EXPOSE 8080
CMD ["npm", "start"]